### PR TITLE
Added "TemplateId" to Invoice.java

### PR DESCRIPTION
**Pull request by MiladSadinam**
Hey, the Invoice Class is missing the TemplateId Attribut. Could you please merge this? And if possible publish a new Version in Maven? Was not sure if you need a test for this change. If so, let me know.

### CODE REVIEW

**Comment by osiegmar** [comment]
Unfortunately it's not that easy.

1) What is the rationale for the change? What bug is fixed / which value does it add?

2) According to the API documentation it seems that `template_id` is nowaydays part of Invoice, Recurring, Offer, Reminder, CreditNote, Confirmation, DeliveryNote and Letter. When I implemented the API the `template_id` was only part of the complete request.

3) The tests regarding `template_id` are based on the `de.siegmar.billomat4j.service.AbstractService#completeDocument` method. What are the implications of your change? Those need to be tested...

4) Maybe related: One of the template tests is currently disabled because of an unknown API change (test regression): https://github.com/osiegmar/billomat4j/blob/8df4b4bdaec2e87a6a6f3aff27da0cda11383dec/src/integrationTest/java/integrationtest/template/TemplateServiceIT.java#L151

**Comment by MiladSadinam** [comment]
The mentioned disabled test doesn't seem to be related to this issue. It is about creating a template and not related to invoices.

**Comment by osiegmar** [comment]
Solved by bba3821c12e677c1d039e38af640fca39db93627 – unfortunately I don't have time for writing automated tests for that.

**Comment by MiladSadinam** [comment]
Thank you for the fix.
And sorry for me not responding. I was also quite busy.

**Pull request closed without merging**
